# Generated by Django 5.0.3 on 2024-04-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_banneer_remove_product_price_productattribute'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banneer',
            options={'verbose_name': '1. Баннеры', 'verbose_name_plural': '1. Баннеры'},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': '3. Бренды', 'verbose_name_plural': '3. Бренды'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '2. Категории', 'verbose_name_plural': '2. Категории'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': '4. Цвета', 'verbose_name_plural': '4. Цвета'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '6. Товары', 'verbose_name_plural': '6. Товары'},
        ),
        migrations.AlterModelOptions(
            name='productattribute',
            options={'verbose_name': '7. Атрибуты товаров', 'verbose_name_plural': '7. Атрибуты товаров'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name': '5. Размеры', 'verbose_name_plural': '5. Размеры'},
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
