# Generated by Django 5.0.3 on 2024-04-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_banneer_options_alter_brand_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banneer',
            name='image',
            field=models.ImageField(upload_to='banner_img/'),
        ),
    ]
