# Generated by Django 5.0.2 on 2024-04-11 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_product_image_productattribute_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='color',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
