# Generated by Django 5.0.3 on 2024-04-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_product_color_remove_productattribute_color_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '5. Товары', 'verbose_name_plural': '5. Товары'},
        ),
        migrations.AlterModelOptions(
            name='productattribute',
            options={'verbose_name': '6. Атрибуты товаров', 'verbose_name_plural': '6. Атрибуты товаров'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name': '4. Размеры', 'verbose_name_plural': '4. Размеры'},
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
