# Generated by Django 5.0.3 on 2024-05-13 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_productreview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productreview',
            options={'verbose_name': '#. Оценки товаров', 'verbose_name_plural': '#. Оценки товаров'},
        ),
    ]
